# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contatos.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'contatos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontatos.proto\x12\x08\x63ontatos\"\x07\n\x05\x45mpty\"@\n\x08Telefone\x12\x0e\n\x06numero\x18\x01 \x01(\t\x12$\n\x04tipo\x18\x02 \x01(\x0e\x32\x16.contatos.TipoTelefone\"m\n\x07\x43ontato\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12%\n\ttelefones\x18\x02 \x03(\x0b\x32\x12.contatos.Telefone\x12-\n\tcategoria\x18\x03 \x01(\x0e\x32\x1a.contatos.CategoriaContato\"4\n\x0e\x43ontatoRequest\x12\"\n\x07\x63ontato\x18\x01 \x01(\x0b\x32\x11.contatos.Contato\"\x1f\n\x0f\x43onsultaRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"G\n\x0f\x43ontatoResponse\x12\"\n\x07\x63ontato\x18\x01 \x01(\x0b\x32\x11.contatos.Contato\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"<\n\x15ListaContatosResponse\x12#\n\x08\x63ontatos\x18\x01 \x03(\x0b\x32\x11.contatos.Contato*7\n\x0cTipoTelefone\x12\t\n\x05MOVEL\x10\x00\x12\x08\n\x04\x46IXO\x10\x01\x12\x12\n\x0eTIPO_COMERCIAL\x10\x02*F\n\x10\x43\x61tegoriaContato\x12\x0c\n\x08\x46\x41MILIAR\x10\x00\x12\x0b\n\x07PESSOAL\x10\x01\x12\x17\n\x13\x43\x41TEGORIA_COMERCIAL\x10\x02\x32\xe7\x01\n\x0e\x43ontatoService\x12G\n\x10\x41\x64icionarContato\x12\x18.contatos.ContatoRequest\x1a\x19.contatos.ContatoResponse\x12H\n\x10\x43onsultarContato\x12\x19.contatos.ConsultaRequest\x1a\x19.contatos.ContatoResponse\x12\x42\n\x0eListarContatos\x12\x0f.contatos.Empty\x1a\x1f.contatos.ListaContatosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contatos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPOTELEFONE']._serialized_start=436
  _globals['_TIPOTELEFONE']._serialized_end=491
  _globals['_CATEGORIACONTATO']._serialized_start=493
  _globals['_CATEGORIACONTATO']._serialized_end=563
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TELEFONE']._serialized_start=37
  _globals['_TELEFONE']._serialized_end=101
  _globals['_CONTATO']._serialized_start=103
  _globals['_CONTATO']._serialized_end=212
  _globals['_CONTATOREQUEST']._serialized_start=214
  _globals['_CONTATOREQUEST']._serialized_end=266
  _globals['_CONSULTAREQUEST']._serialized_start=268
  _globals['_CONSULTAREQUEST']._serialized_end=299
  _globals['_CONTATORESPONSE']._serialized_start=301
  _globals['_CONTATORESPONSE']._serialized_end=372
  _globals['_LISTACONTATOSRESPONSE']._serialized_start=374
  _globals['_LISTACONTATOSRESPONSE']._serialized_end=434
  _globals['_CONTATOSERVICE']._serialized_start=566
  _globals['_CONTATOSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
