# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contatos_pb2 as contatos__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contatos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContatoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AdicionarContato = channel.unary_unary(
                '/contatos.ContatoService/AdicionarContato',
                request_serializer=contatos__pb2.ContatoRequest.SerializeToString,
                response_deserializer=contatos__pb2.ContatoResponse.FromString,
                _registered_method=True)
        self.ConsultarContato = channel.unary_unary(
                '/contatos.ContatoService/ConsultarContato',
                request_serializer=contatos__pb2.ConsultaRequest.SerializeToString,
                response_deserializer=contatos__pb2.ContatoResponse.FromString,
                _registered_method=True)
        self.ListarContatos = channel.unary_unary(
                '/contatos.ContatoService/ListarContatos',
                request_serializer=contatos__pb2.Empty.SerializeToString,
                response_deserializer=contatos__pb2.ListaContatosResponse.FromString,
                _registered_method=True)


class ContatoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AdicionarContato(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarContato(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarContatos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContatoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AdicionarContato': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarContato,
                    request_deserializer=contatos__pb2.ContatoRequest.FromString,
                    response_serializer=contatos__pb2.ContatoResponse.SerializeToString,
            ),
            'ConsultarContato': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarContato,
                    request_deserializer=contatos__pb2.ConsultaRequest.FromString,
                    response_serializer=contatos__pb2.ContatoResponse.SerializeToString,
            ),
            'ListarContatos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarContatos,
                    request_deserializer=contatos__pb2.Empty.FromString,
                    response_serializer=contatos__pb2.ListaContatosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contatos.ContatoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contatos.ContatoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContatoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AdicionarContato(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contatos.ContatoService/AdicionarContato',
            contatos__pb2.ContatoRequest.SerializeToString,
            contatos__pb2.ContatoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarContato(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contatos.ContatoService/ConsultarContato',
            contatos__pb2.ConsultaRequest.SerializeToString,
            contatos__pb2.ContatoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarContatos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contatos.ContatoService/ListarContatos',
            contatos__pb2.Empty.SerializeToString,
            contatos__pb2.ListaContatosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
